[project]
name = "odoo-addons-oca-rest-framework"
version = "18.0.20250203.0"
dependencies = [
    "odoo-addon-fastapi==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
